BD:
  smartsys:
    host:
    port: 5432
    dbname: smartsys
    user: smartsys
    password:
  sms:
    host:
    port: 5432
    dbname: smsd
    user: smsd
    password:
sys:
  log_path: /var/log/smartsys/
  tg_token:
  debug_mod: 1
  test_mod: 0
  debug_msg_mod: 0
i2c:
  port: 1
  pt:
    1: 0x76